### This creates the table to gather tablespace growth
CREATE TABLE AWH_TBS_GROWTH_PROJ 
   (	HOST_NAME       	VARCHAR2(64), 
	DB_NAME         	VARCHAR2(16), 
	PDB_NAME        	VARCHAR2(32), 
	TABLESPACE_NAME 	VARCHAR2(100), 
	ALLOC_SZ_MB     	NUMBER, 
	USED_SZ_MB      	NUMBER, 
	AVG_GROWTH_PER_DAY_MB 	NUMBER, 
	PROJECTED_GROWTH_3MO_MB NUMBER, 
	FREE_SZ_MB      	NUMBER, 
	MSG             	VARCHAR2(9), 
	PROJECTED_GROWTH_6MO_MB	NUMBER, 
	PROJECTED_GROWTH_1YR_MB NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE <AWH_TBS> ;
